### PR TITLE
Fix transforms for static objects

### PR DESCRIPTION
**Pull request by sasha240100**
**Static rigidbodies don't update their transforms.**
I made a commit that resolves by setting the initial transforms state (`body.pos`, `body.quat`) used in `.getPosition()` & `.getRotation()` to be equal to `body.position` and `body.orientation`.

----

And i added `Plane` and `Particle` to exports. Anyway they are used in the code so why not to export them. Personally i would like to see them in Oimo.js)

### CODE REVIEW

**Comment by lo-th** [comment]
yes thank for transform fix but i made many change since you fix 
i include in last revision 

for plane and particle is not yet implemented 
do collision for each shape is hard

**Comment by sasha240100** [comment]
@lo-th okay, can you point me to those changes so I can update my fork? Also I would like to contribute to this project (I think about possibility of adding new shapes and improving performance)

**Comment by lo-th** [comment]
cool ok, i think update soon 
i fix sphere cylinder / on world i fix remove i add intenal update for main demo

**Comment by lo-th** [comment]
mm is not good pos need to be change at setParent 
for correct world scale

**Comment by sasha240100** [comment]
@lo-th You know, i am making a [physics module based on oimojs](https://github.com/WhitestormJS/physics-module-oimojs) for [my framework](https://github.com/WhitestormJS/whitestorm.js). I want to improve current integration situation in web's 3D (make it simpler). So i will contribute to Oimo.js and would like to improve it.

If you'd like to contribute to my project - let's discuss it)
I have some questions about Oimo.js can we discuss them in real-time chat? Facebook messanger / slack / discord ?

**Comment by lo-th** [comment]
ok is done

**Comment by lo-th** [comment]
oimo is far from possibility of ammo for the moment 
maybe with next update from saharan

**Comment by sasha240100** [comment]
@lo-th That's why I develop a physics module to wrap it. I already have a one for ammo and I want to also have a  simple lightweight library like Oimo.js. Wrapping with physics module means that they will have near the same module API for whitestormjs. So people will be able to easily switch from one to another and choose the one that fits

**Comment by lo-th** [comment]
yea i see, i make something like that 
with https://github.com/lo-th/Ammo.lab

code editor is near

**Pull request closed without merging**
